In [8]:
class BinarySearchTree:
    def __init__(self):
        self.root = None
        self.size = 0

    def length(self):
        return self.size

    def __len__(self):
        return self.size

    def __iter__(self):
        return self.root.__iter__()

In [9]:
class TreeNode:
    def __init__(self, key, val, left = None, 
                 right = None, parent = None):
        self.key        = key
        self.payload    = val
        self.leftChild  = left
        self.rightChild = right
        self.parent     = parent
        
    def hasLeftChild(self):
        return self.leftChild
    
    def hasRightChild(self):
        return self.rightChild
    
    def isRoot(self):
        return not self.parent
    
    def isLeaf(self):
        return not (self.leftChild or self.rightChild)
    
    def hasAnyChildren(self):
        return self.leftChild or self.rightChild
    
    def hasBothChildren(self):
        return self.leftChild and self.rightChild
    
    def replaceNodeData(self, key, value, lc, rc):
        self.key = key
        self.payload = value
        self.leftChild = lc
        self.rightChild = rc
        if self.hasLeftChild():
            self.leftChild.parent = self
        if self.hasRightChild():
            self.rightChild.parent = self

In [10]:
class RITNode:
    def __init__(self, key, val, parent=None):
        self.key = key
        self.val = val
        self.parent = parent

    def isLeaf(self):
        return not self.hasChildren

    def isParent(self):
        return self.hasChildren

    def hasChildren(self):
        return self.numChildren > 0

    # Need to define childList - how?!
    def numChildren(self):
        return len(self.childList)

    def isRoot(self):
        return not self.parent
    
    # The childlist would be 0 indexed. So nth child
    # is the (n-1)th index
    def nthChild(self, n):        
        return self.childList[n - 1]

In [ ]:
class RIT:
    def __init__(self, max_depth = 3, paths_list = None,
                num_splits = 2):
        self.max_depth  = max_depth
        self.paths_list = paths_list
        self.num_splits = num_splits
        self.tree_depth = 0
        
    def insertIntersectChild(self):
        # insert and Intersect child
        pass
    
    def 
        
        
        

In [2]:
import numpy as np

In [38]:
X = np.random.random(size=(80, 100)) > 0.3

In [39]:
X

array([[ True, False,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True, False,  True],
       ..., 
       [ True,  True,  True, ...,  True, False,  True],
       [ True,  True, False, ...,  True, False,  True],
       [ True,  True, False, ..., False,  True,  True]], dtype=bool)

In [40]:
XX = [np.nonzero(row)[0] for row in X]
XX

[array([ 0,  2,  3,  4,  6,  7, 14, 15, 17, 18, 20, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 45, 46, 47,
        50, 52, 53, 54, 58, 61, 62, 63, 64, 65, 67, 68, 69, 71, 72, 73, 74,
        75, 77, 79, 81, 82, 83, 84, 85, 86, 87, 88, 90, 91, 92, 96, 97, 98,
        99]),
 array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 11, 12, 14, 17, 18, 22, 25, 27,
        30, 33, 34, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 50, 53, 54,
        55, 56, 57, 58, 59, 60, 62, 63, 65, 66, 68, 72, 74, 75, 77, 78, 79,
        80, 82, 84, 86, 87, 89, 93, 94, 96, 97, 98, 99]),
 array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 15, 17, 18, 19,
        20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 38, 39,
        42, 43, 44, 45, 47, 48, 50, 51, 52, 53, 55, 56, 57, 58, 59, 60, 61,
        62, 63, 65, 67, 68, 69, 72, 73, 75, 77, 78, 79, 80, 82, 84, 86, 87,
        88, 89, 90, 91, 92, 94, 95, 96, 97, 99]),
 array([ 0,  1,  3,  4,  7,  8, 11, 12, 13

In [182]:
#class select_random_path(object):    
#    def __call__(self):
#        while True:
#            self.cnt += 1
#            yield XX[np.random.randint(low=0, high=len(XX))]

def select_random_path():    
    while True:
        yield XX[np.random.randint(low=0, high=len(XX))]

In [426]:
class RITNode(object):
    def __init__(self, val):
        self._val = val
        self._children = []

    def is_leaf(self):
        return len(self._children) == 0

    @property
    def children(self):
        return self._children
    
    def add_child(self, val):
        val_intersect = np.intersect1d(self._val, val)
        self._children.append(RITNode(val_intersect))
        
    def is_empty(self):
        return len(self._val) == 0
        
    def is_leaf(self):
        return len(self._children) == 0
    
    @property
    def nr_children(self):
        return len(self._children) + sum(child.nr_children for child in self._children)
    
    def _traverse_depth_first(self, _idx):
        yield _idx[0], self
        for child in self.children:
            _idx[0] += 1
            yield from RITNode._traverse_depth_first(child, _idx=_idx)    

class RITTree(RITNode):
    def __len__(self):
        return self.nr_children + 1
    
    def traverse_depth_first(self):
        yield from RITNode._traverse_depth_first(self, _idx=[0])

In [427]:
from functools import partial

def build_tree(feature_paths, max_depth=3, num_splits=5, noisy_split=False, _parent=None, _depth=0):
    """
    Parameters
    ----------
    feature_paths : generator of list of ints
        ...
    max_depth : int
        The built tree will never be deeper than `max_depth`.
    num_splits : int
        At each node, the maximum number of children to be added.
    """
    expand_tree = partial(build_tree, feature_paths, max_depth=max_depth,
                          num_splits=num_splits, noisy_split=noisy_split)
    
    if _parent is None:
        tree = RITTree(next(feature_paths))
        expand_tree(_parent=tree, _depth=0)
        return tree
    else:
        _depth += 1
        if _depth >= max_depth:
            return
        if noisy_split:
            num_splits += np.random.randint(low=0, high=2)
        for i in range(num_splits):
            _parent.add_child(next(feature_paths))
            added_node = _parent.children[-1]
            if not added_node.is_empty():
                expand_tree(_parent=added_node, _depth=_depth)

In [451]:
np.random.seed(12)
tree = build_tree(feature_paths=select_random_path(), max_depth=3, noisy_split=False, num_splits=5)
#path_gen = select_random_path()
#tree = build_tree(feature_paths=path_gen(), max_depth=3, num_splits=5)

In [445]:
#%timeit build_tree(feature_paths=select_random_path())

In [446]:
print("Root:\n", tree._val)
print("Some child:\n", tree.children[0].children[1]._val)

Root:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 13 14 16 17 19 22 26 29 30 34 35 36 39
 40 41 42 45 47 49 51 52 53 54 55 57 59 60 61 62 64 70 72 74 76 78 81 82 84
 85 86 87 88 89 91 93 94 95 96 97]
Some child:
 [ 0  1  2  4  5  7  8 13 17 19 22 26 29 35 36 42 47 52 53 55 57 59 60 61 62
 78 84 86 87 89 95 96]


In [452]:
# If noisy split is False, this should pass
assert(len(tree) == 1 + 5 + 5**2)

In [450]:
# If noisy split is True, this should pass
print(len(tree))
assert(len(tree) <= 1 + 6 + 6**2)

40


In [436]:
list(tree.traverse_depth_first())

[(0, <__main__.RITTree at 0x115e18cf8>),
 (1, <__main__.RITNode at 0x115e1ab70>),
 (2, <__main__.RITNode at 0x115e18358>),
 (3, <__main__.RITNode at 0x115e18c88>),
 (4, <__main__.RITNode at 0x115e18470>),
 (5, <__main__.RITNode at 0x115e18eb8>),
 (6, <__main__.RITNode at 0x115e1a518>),
 (7, <__main__.RITNode at 0x115e1a5c0>),
 (8, <__main__.RITNode at 0x115e1ae80>),
 (9, <__main__.RITNode at 0x115e1a550>),
 (10, <__main__.RITNode at 0x115f79400>),
 (11, <__main__.RITNode at 0x115f79dd8>),
 (12, <__main__.RITNode at 0x115f79908>),
 (13, <__main__.RITNode at 0x115f79550>),
 (14, <__main__.RITNode at 0x115f79390>),
 (15, <__main__.RITNode at 0x115f797b8>),
 (16, <__main__.RITNode at 0x115f79e10>),
 (17, <__main__.RITNode at 0x115f79128>),
 (18, <__main__.RITNode at 0x115f79588>),
 (19, <__main__.RITNode at 0x115f79f60>),
 (20, <__main__.RITNode at 0x115f79b00>),
 (21, <__main__.RITNode at 0x115f79320>),
 (22, <__main__.RITNode at 0x115f79198>),
 (23, <__main__.RITNode at 0x115f79048>),
 (

In [424]:

        
def breadth_first

SyntaxError: invalid syntax (<ipython-input-424-3e83776d094d>, line 3)